version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - codecalm
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: stylelint
    versions:
    - 13.8.0
    - 13.9.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: nodemon
    versions:
    - 2.0.6
  - dependency-name: lodash
    versions:
    - 4.17.20
